name: karaoke_wishlist_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  http: ^0.13.0
  xml: 6.1.0
  mysql1: ^0.20.0
  crypt: ^4.2.1
  shelf_cors_headers: ^0.1.4
  dotenv: ^3.0.0
  path: ^1.8.3
  file_hasher: ^0.1.0+0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
